# #####################################################################
# Automatically generated by qmake (2.01a) dom gen 17 03:03:33 2010
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += qtestlib
QT -= gui

# Input
HEADERS += ../fixedpoint.h \
    ../fixedpoint/stringify.h \
    ../fixedpoint/fputils.h \
    ../fixedpoint/anyint.h
SOURCES += test.cpp
